/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Registers a new user account. After successful registration, an activation email will be sent to the provided email address. The user must activate their account before being able to log in.
     */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Authenticates a user with email and password credentials. Upon successful authentication, a session cookie is created and returned in the response headers. The user must have an activated account to log in.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Terminates the current user session by invalidating the session cookie. The user will need to log in again to access protected endpoints.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Activates a user account using the activation token sent via email during registration. Once activated, the user can log in to the application.
     */
    post: operations["activate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/resend-activation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Resends the account activation email to the specified email address when the original activation email was not received or has expired.
     */
    post: operations["resend_activation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Initiates the password reset process by sending a password reset email to the specified email address. The email contains a unique reset token that can be used to set a new password.
     */
    post: operations["forgot_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PUBLIC ENDPOINT***
     *
     *     Completes the password reset process by setting a new password using the reset token received via email.
     */
    post: operations["reset_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/user/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves the complete profile information of the currently authenticated user.
     */
    get: operations["get_user_profile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/board/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves a list of all boards where the authenticated user is a member.
     */
    get: operations["get_user_boards"];
    put?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Creates a new Kanban board. The authenticated user automatically becomes the owner with full permissions.
     */
    post: operations["create_board"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/board/{boardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves detailed information about a specific board by its ID. Only board members can access this endpoint.
     */
    get: operations["get_board"];
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Updates board information. Only the board owner and moderator can update board details.
     */
    put: operations["update_board"];
    post?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Permanently deletes a board and all its associated data (columns, tasks, and members). Only the board owner can delete boards. This action cannot be undone.
     */
    delete: operations["delete_board"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/board/member": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Updates a board member's role. Only the board owner can modify member roles. The board owner cannot change their own role.
     */
    put: operations["update_board_member_role"];
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Adds a new member to a board by user ID. Only the board owner and moderator can add new members. The new member will have the default member role and can be changed later.
     */
    post: operations["add_new_board_member"];
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Removes a member from a board. Only the board owner can remove members. The board owner cannot remove themselves - to leave as owner, transfer ownership first or delete the board.
     */
    delete: operations["remove_board_member"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/column/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Creates a new column within a board. The column will be positioned at the end of the board. Only the board owner and moderator can create columns.
     */
    post: operations["create_column"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/column/{columnId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves detailed information about a specific column by its ID. User must be a member of the board to access this endpoint.
     */
    get: operations["get_column"];
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Updates column information. Only the board owner and moderator can update column details.
     */
    put: operations["update_column"];
    post?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Permanently deletes a column and all its associated tasks. Remaining columns will be automatically reordered. This action cannot be undone. Only the board owner and moderator can create columns.
     */
    delete: operations["delete_column"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/column/board/{boardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves all columns for a specific board, ordered by their position. User must be a member of the board to access this endpoint.
     */
    get: operations["get_board_columns"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/column/{columnId}/move/{position}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Moves a column to a new position within the board. Other columns will be automatically reordered. Position is 0-indexed. Only the board owner and moderator can create columns.
     */
    put: operations["move_column"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/task/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Creates a new task within a column. The task will be positioned at the end of the column. All board members can create tasks.
     */
    post: operations["create_task"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/task/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves detailed information about a specific task by its ID. User must be a member of the board to access this endpoint.
     */
    get: operations["get_task"];
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Updates task information. All board members can update tasks.
     */
    put: operations["update_task"];
    post?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Permanently deletes a task. This action cannot be undone. All board members can delete tasks.
     */
    delete: operations["delete_task"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/task/column/{columnId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Retrieves all tasks for a specific column, ordered by their position. User must be a member of the board to access this endpoint.
     */
    get: operations["get_column_tasks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/task/{taskId}/move/{columnId}/{position}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Moves a task to a new position within the same column or to a different column. Position is 0-indexed. All board members can move tasks.
     */
    put: operations["move_task"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ws/board/{boardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description ***PROTECTED ENDPOINT***
     *
     *     Establishes a WebSocket connection for real-time board updates. The connection enables bidirectional communication for live collaboration features such as task updates, column changes, and member activities. User must be a member of the board to establish the connection.
     */
    get: operations["websocket_handler"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ActivationQueryDto: {
      userId: string;
      activationToken: string;
    };
    AddBoardMemberDto: {
      /** Format: uuid */
      boardId: string;
      /** Format: uuid */
      userId: string;
    };
    ApiResponseSchema_BoardDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        name: string;
        description?: string | null;
        /** Format: uuid */
        ownerId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      };
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_BoardMemberDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        /** Format: uuid */
        boardId: string;
        /** Format: uuid */
        userId: string;
        role: components["schemas"]["BoardMemberRoleEnum"];
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      };
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_ColumnDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        name: string;
        position: string;
        /** Format: uuid */
        boardId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      };
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_String: {
      message: string;
      data?: string;
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_TaskDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        title: string;
        description?: string | null;
        tags?: string[] | null;
        position: string;
        /** Format: uuid */
        columnId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      };
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_UserDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        isActive: boolean;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      };
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_Vec_BoardDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        name: string;
        description?: string | null;
        /** Format: uuid */
        ownerId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      }[];
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_Vec_ColumnDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        name: string;
        position: string;
        /** Format: uuid */
        boardId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      }[];
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_Vec_TaskDto: {
      message: string;
      data?: {
        /** Format: uuid */
        id: string;
        title: string;
        description?: string | null;
        tags?: string[] | null;
        position: string;
        /** Format: uuid */
        columnId: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        updatedAt: string;
      }[];
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApiResponseSchema_u64: {
      message: string;
      /** Format: int64 */
      data?: number;
      /** Format: int64 */
      rowsAffected?: number | null;
      /** Format: int64 */
      page?: number | null;
      /** Format: int64 */
      totalPages?: number | null;
    };
    ApplicationErrorSchema: {
      /** Format: int32 */
      statusCode: number;
      error: string;
      message: string;
    };
    BoardDto: {
      /** Format: uuid */
      id: string;
      name: string;
      description?: string | null;
      /** Format: uuid */
      ownerId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    BoardMemberDto: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      boardId: string;
      /** Format: uuid */
      userId: string;
      role: components["schemas"]["BoardMemberRoleEnum"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    BoardMemberRoleEnum: "owner" | "moderator" | "member";
    ColumnDto: {
      /** Format: uuid */
      id: string;
      name: string;
      position: string;
      /** Format: uuid */
      boardId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateBoardDto: {
      name: string;
      description?: string | null;
    };
    CreateColumnDto: {
      name: string;
      /** Format: uuid */
      boardId: string;
    };
    CreateTaskDto: {
      title: string;
      description?: string | null;
      tags?: string[] | null;
      /** Format: uuid */
      columnId: string;
    };
    CreateUserDto: {
      email: string;
      password: string;
      firstName: string;
      lastName: string;
    };
    DeleteBoardMemberDto: {
      /** Format: uuid */
      boardId: string;
      /** Format: uuid */
      userId: string;
    };
    ForgotPasswordQueryDto: {
      email: string;
    };
    LoginDto: {
      email: string;
      password: string;
    };
    ResendActivationQueryDto: {
      email: string;
    };
    ResetPasswordDto: {
      userId: string;
      resetToken: string;
      newPassword: string;
    };
    TaskDto: {
      /** Format: uuid */
      id: string;
      title: string;
      description?: string | null;
      tags?: string[] | null;
      position: string;
      /** Format: uuid */
      columnId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateBoardDto: {
      name?: string | null;
      description?: string | null;
    };
    UpdateBoardMemberRoleDto: {
      /** Format: uuid */
      boardId: string;
      /** Format: uuid */
      userId: string;
      role: components["schemas"]["BoardMemberRoleEnum"];
    };
    UpdateColumnDto: {
      name?: string | null;
    };
    UpdateTaskDto: {
      title?: string | null;
      description?: string | null;
      tags?: string[] | null;
    };
    UserDto: {
      /** Format: uuid */
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description Created - User registered successfully. An activation email has been sent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_UserDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Conflict - User with this email address already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to create user or send activation email */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description OK - User logged in successfully. Session cookie has been set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_UserDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Account is not activated */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to create user session */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - User logged out successfully. Session has been terminated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_String"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  activate: {
    parameters: {
      query: {
        /** @description Unique identifier of the user */
        userId: string;
        /** @description Unique activation token */
        activationToken: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Account activated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_UserDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to activate account */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  resend_activation: {
    parameters: {
      query: {
        /** @description Email address of the user */
        email: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Activation email resent successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_String"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - User with the given email address not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Conflict - Account is already activated */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Too Many Requests - Activation email resend limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to send activation email */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  forgot_password: {
    parameters: {
      query: {
        /** @description Email address of the user */
        email: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Password reset email sent successfully. Check your inbox for further instructions. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_String"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - Account is not activated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - User with the given email address not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Too Many Requests - Password reset email request limit exceeded */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to send password reset email */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  reset_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordDto"];
      };
    };
    responses: {
      /** @description OK - Password reset successfully. You can now log in with your new password */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_String"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to reset password */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_user_profile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - User profile retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_UserDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - User with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to retrieve user profile */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_user_boards: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Boards retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_Vec_BoardDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to retrieve boards */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  create_board: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBoardDto"];
      };
    };
    responses: {
      /** @description Created - Board created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_BoardDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to create board */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_board: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the board */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Board data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_BoardDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - Board with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to retrieve board */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  update_board: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the board */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBoardDto"];
      };
    };
    responses: {
      /** @description OK - Board updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_BoardDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Only board owner and moderator can update board details */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - Board with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to update board */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  delete_board: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the board */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Board deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_u64"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Only board owner can delete boards */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - Board with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to delete board */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  update_board_member_role: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBoardMemberRoleDto"];
      };
    };
    responses: {
      /** @description OK - Board member role updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_BoardMemberDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Only board owner can update member roles */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - The specified user is not a member of this board */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to update board member role */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  add_new_board_member: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddBoardMemberDto"];
      };
    };
    responses: {
      /** @description Created - Board member added successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_BoardMemberDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Only board owner and moderator can add members */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - Board or user with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to add board member */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  remove_board_member: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteBoardMemberDto"];
      };
    };
    responses: {
      /** @description OK - Board member removed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_u64"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - Only board owner can remove members */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not found - The specified user is not a member of this board */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Conflict - Cannot remove yourself from the board */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal server error - Failed to remove board member */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  create_column: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateColumnDto"];
      };
    };
    responses: {
      /** @description Created - Column created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_ColumnDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have permission to create columns in this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Board with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to create column */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_column: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the column */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Column data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_ColumnDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to the board containing this column */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to retrieve column */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  update_column: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the column */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateColumnDto"];
      };
    };
    responses: {
      /** @description OK - Column updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_ColumnDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have permission to update columns in this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to update column */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  delete_column: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the column */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Column deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_u64"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have permission to delete columns in this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to delete column */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_board_columns: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the board */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Columns retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_Vec_ColumnDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to retrieve columns */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  move_column: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the column */
        columnId: string;
        /** @description New position index for the column (0-based) */
        position: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Column moved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_ColumnDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have permission to reorder columns in this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to move column */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  create_task: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskDto"];
      };
    };
    responses: {
      /** @description Created - Task created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_TaskDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to create task */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the task */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Task data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_TaskDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Task with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to retrieve task */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  update_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the task */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTaskDto"];
      };
    };
    responses: {
      /** @description OK - Task updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_TaskDto"];
        };
      };
      /** @description Bad Request - Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Task with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to update task */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  delete_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the task */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Task deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_u64"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Task with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to delete task */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  get_column_tasks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the column */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Tasks retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_Vec_TaskDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to retrieve tasks */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  move_task: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the task */
        taskId: string;
        /** @description Unique identifier of the column */
        columnId: string;
        /** @description New position index for the column (0-based) */
        position: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK - Task moved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseSchema_TaskDto"];
        };
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User doesn't have access to this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Task or column with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to move task */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
  websocket_handler: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Unique identifier of the board */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Switching Protocols - WebSocket connection established successfully */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized - No active session or session has expired */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Forbidden - User is not a member of this board */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Not Found - Board with the given ID not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
      /** @description Internal Server Error - Failed to establish WebSocket connection */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApplicationErrorSchema"];
        };
      };
    };
  };
}
